FROM arm32v7/ubuntu:latest

RUN apt-get -y update
RUN apt-get install -y libx11-dev \
	libxext-dev \
	libc6-dev \
	gcc

# if on i386 there's no need for multilib
#RUN apt-get install -y libc6-dev-i386
#RUN apt-get install -y libx11-6:i386, libxext-dev:i386
#RUN apt-get install -y gcc-multilib

ENV INFERNO=/usr/inferno
COPY . $INFERNO
WORKDIR $INFERNO

# setup a custom mkconfig
RUN echo > mkconfig ROOT=$INFERNO  \
    && echo >>mkconfig TKSTYLE=std \
    && echo >>mkconfig SYSHOST=Linux  \
    && echo >>mkconfig SYSTARG=Linux  \
    && echo >>mkconfig OBJTYPE=arm    \
    && echo >>mkconfig 'OBJDIR=$SYSTARG/$OBJTYPE'  \
    && echo >>mkconfig '<$ROOT/mkfiles/mkhost-$SYSHOST' \
    && echo >>mkconfig '<$ROOT/mkfiles/mkfile-$SYSTARG-$OBJTYPE' 

# build code
#RUN ./makemk.sh
ENV PATH="$INFERNO/Linux/arm/bin:${PATH}"
#RUN mk nuke
#RUN mk install

CMD ["emu", "-c1",  "wm/wm"]

